version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install
      - echo Installing NGINX
      - sudo yum update
      - sudo yum install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
      - echo Starting Node.js app
      - npm run build || echo "No build step defined"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    

