version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - mkdir /home/ec2-user/node-app/
      - cp index.html /home/ec2-user/node-app/
      - npm run build || echo No build script defined
      
artifacts:
  files:
    - '**/*'
  discard-paths: no
